owner: Rashi228
repo: ims-status

sites:
  - name: Frontend UI Portal
    url: https://ims-frontend-1053994989870.us-central1.run.app
  - name: Backend API Server
    url: https://ims-backend-1053994989870.us-central1.run.app/docs
  - name: Supabase Database (Deep Check)
    url: https://ims-backend-1053994989870.us-central1.run.app/health

status-website:
  name: IMS System Status
  introTitle: "**Incident Management System** Real-Time Status"
  introMessage: Welcome to the public status page for the Enterprise IMS. If there are any service outages, they will be reported here automatically.
  theme: light
  navbar:
    - title: Status
      href: /
    - title: Main Project Code
      href: https://github.com/Rashi228/Incident-Management-System

i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All Systems Operational
  incidentReport: "Incident Report #$NUMBER"
  activeIncidentSummary: Opened at $DATE with $POSTS posts.
  incidentTitle: Incident Details
